### PR TITLE
Issue 427 - Reverting Some Thread Pool Changes To version 2.51.0

### PR DESCRIPTION
**Pull request by naphelps**
References: #427 

Changes:
- Reverting Some Thread Pool Changes To version 2.51.0

### CODE REVIEW

**Comment by naphelps** [comment]
Passed all local tests.

**Review by sf2ne — APPROVED** [review]
lgtm

**Comment by sf2ne** [comment]
Waiting on e2edev to finish

**Review by bmpotter — APPROVED** [review]

**Comment by sf2ne** [comment]
Passed local e2edev

**Pull request merged**
